server:
  port: 8089

spring:
#  数据库连接信息
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
#  更改启动的图标springboot为fighting
  banner:
    location: banner/banner.txt

  boot:
    admin:
      client:
        url: http://localhost:8080
  ## application实例名
  application:
    name : spring-boot-admin-client
#  mybatis配置
mybatis:
  mapper-locations: classpath:/mapper/*Dao.xml

# 下面用于开启所有监控端点。默认情况下，所有的都是关闭的
management:
  endpoints:
    web:
      exposure:
        include: "*"



